# Generated by Django 4.1 on 2022-08-15 05:25

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
