# Generated by Django 4.1 on 2022-08-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('arrived', 'Arrived'), ('trandy', 'Trandy')], max_length=200, null=True),
        ),
    ]
